# -*- coding: utf-8 -*-

POKER_MUTEX_TIMEOUT = 20
POKER_MUTEX_KEY_PREFIX = 'MUTEX_POCKER_'
POKER_IMAGEMAP_ELEMENT_WIDTH = 260
POKER_IMAGEMAP_ELEMENT_HEIGHT = 263
VOTE_MUTEX_TIMEOUT = 10
VOTE_MUTEX_KEY_PREFIX = 'MUTEX_VOTE_'
POKER_IMAGE_FILENAME = 'pp-{$size}.png'


